[env]
TERM = "xterm-256color"

[font]
size = 8

[font.normal]
family = "Hack Nerd Font"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[scrolling]
history = 5000

[window]
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
